apiVersion: apps/v1
kind: Deployment
metadata:
  name: psuite
  labels:
    app: psuite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psuite
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: psuite
    spec:
      hostname: psuite
      serviceAccountName: psuite
      initContainers:
      - name: init-syncthing
        image: rclone/rclone:1.61
        command: ['sh', '/scripts/init-syncthing-config.sh']
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts/
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      containers:
      - name: psuite
        image: linuxserver/syncthing:1.22.2
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: init-scripts
        configMap:
          name: init-scripts
          items:
          - key: init-syncthing-config.sh
            path: init-syncthing-config.sh
      - name: data
        persistentVolumeClaim:
          claimName: psuite-data
      - name: config
        persistentVolumeClaim:
          claimName: psuite-config
